### ISSUE TITLE
x264enc is using multiple slices

### ISSUE THREAD

**Issue by david74chou** [Ullaakut/RTSPAllTheThings#39]
Good job! RTSPATT is a great tool and its pattern mode is quite useful for auto testing.

However, I found current pipeline will set x264enc with `tune=zerolatency` which will make it uses 4 slices for one frame. I am not sure this is expected or not because multiple-slices is rarely used in the surveillance industry (Please correct me if I am wrong). Although ffplay and vlc could handle it correctly, [OpenRTSP](http://www.live555.com/openRTSP/) from live555 would generate invalid mp4.

Please consider to remove `tune=zerolatency` or set it to be single slice so that live555 could handle it correctly.

Thanks

**Comment by Gegonz** [comment]
Hi David,

The best approach would be encoder parameters according to the kind of input that you received or user defined.
For now *tune=zerolatency* was specify to broadcast a RTSP stream (RTSPATT received an RTSP stream and forward it) with as little latency as possible. But I agree it should not be by default, I will do a PR to remove it.
