### ISSUE TITLE
Documenting about the kind of RTP

### ISSUE THREAD

**Issue by frallain** [Ullaakut/RTSPAllTheThings#53]
Hi again, 
It would be nice to document what kind of RTP is done here : RTP/UDP or RTP/TCP or RTP over HTTP ?

I suppose it's RTP/TCP.

**Comment by Ullaakut** [comment]
That's a fair point. It is currently over TCP, yes!

**Comment by Ullaakut** [comment]
Fixed in https://github.com/Ullaakut/RTSPAllTheThings/pull/55
