### ISSUE TITLE
Streaming from an RTSP source no longer works

### ISSUE THREAD

**Issue by Ullaakut** [Ullaakut/RTSPAllTheThings#54]
Not sure why, but when I tried streaming a file with one RTSPATT and use the first RTSPATT as the second one's source, it didn't work, with or without encoding.

**Comment by idulsky** [comment]
I also faced the same problem. I can't make it to re-stream rtsp from IP camera
Ran container via
`docker run --rm -p 8554:8554 -e INPUT="rtsp://xxx:xxx@192.168.174.193" -e RTSP_PORT=8554 ullaakut/rtspatt`
It responded, that Stream ready at rtsp://localhost:8554/live.sdp
But when I tried to play this stream, VLC said
`live555 demux error: Failed to connect with rtsp://localhost:8554/live.sdp`
On the other hand INPUT via pattern worked as expected. Any workaround?

**Comment by Ullaakut** [comment]
Unfortunately not, and I'm really not sure how to fix it. I tried a few solutions already but I don't have enough time at the moment to spend more time on this :( If someone has an idea on how to fix this, feel free to pick it up

**Comment by molobrakos** [comment]
Thanks for your work on this excellent package!

I saw this issue reported and just want to add that RTSP streaming works perfectly fine for me. I am streaming RTSP from a cheap web camera (50H20L_S39), using RTSPatt to multiplex to multiple streams fed into [motioneye](https://github.com/ccrisan/motioneye)/[motion](github).

I did some minor changes, such as switching to docker multistage builds and using `debian-slim` (hade to disable digest support) as a base image [here](https://github.com/Ullaakut/RTSPAllTheThings/compare/master...molobrakos:master).

**Comment by Ullaakut** [comment]
Hi @molobrakos ! Glad it works for you, to be honest I'm not sure at all what is the cause of the problem, it seems to depend on the encoding of the source.

Since you mentioned it, feel free to open a PR with the multi stage docker build! 🙂The size of the current image is quite problematic in my opinion, but I never got around to changing the Dockerfile.

I'll look into this RTSP source issue today once more, and I'll update this issue if I find any clue on what's going on!

**Comment by molobrakos** [comment]
I'll open a PR for the multistage build.
Switching from ubuntu to debian-slim shaves off quite a bit from the image size, but the gstreamer version in that image didn't seem to support quite the same api regarding the digest stuff. Maybe the testing-slim or unstable-slim images could work, but I did not try that.

**Comment by Ullaakut** [comment]
Thanks very much! 🎉 

Perhaps the solution is to manually install a more recent version of gstreamer in the build process, to have access to the newer features of the API. Don't worry about it though, if you open the PR for the multi stage build I'll try and figure out how to install it manually, I think I've done it before I just have to find the Dockerfile!

**Comment by softdev87** [comment]
Why was this closed ? Seems to still be an issue.

**Comment by fox365** [comment]
Same issue for me running:
`docker run --rm -e INPUT="rtsp://user:pass@192.168.1.100:554/cam/realmonitor?channel=1&su
btype=0&unicast=true" -e RTSP_PORT=8554 ullaakut/rtspatt`

Returns:
`Stream ready at rtsp://0.0.0.0:8554/live.sdp`

But in VLC...
`live555 error: Failed to connect with rtsp://localhost:8554/live.sdp
access_realrtsp error: cannot connect to localhost:8554
core error: open of `rtsp://localhost:8554/live.sdp' failed`

**Comment by birdage** [comment]
Also getting the same issue...

**Comment by Ullaakut** [comment]
In the end I didn't find the time to work on a version that has both the digest feature and the RTSP broadcasting features, but in the meantime for you guys I can maybe make a separate tag especially for RTSP broadcasting using @molobrakos's dockerfile?

What do you think? @birdage @fox365

**Comment by birdage** [comment]
That works!

**Comment by Ullaakut** [comment]
I pushed it with the tag `ullaakut/rtspatt:broadcast`, could you give it a try and let me know if it works for you? :)
