### ISSUE TITLE
re-streamming from ipcam (rtsp) has no audio

### ISSUE THREAD

**Issue by sidisrikk** [Ullaakut/RTSPAllTheThings#60]
I capture stream by vlc player. Here is [screenshot](https://ibb.co/bOVsdp) media info from direct ipcam  and [screenshot](https://ibb.co/jfvayp
) from rtspatt .

I found rtspatt use Gstreamer so i google for awhile but that too complex i can't understand haha
But atleast i have some clues   [1](https://stackoverflow.com/a/29050060)   [2](http://gstreamer-devel.966125.n4.nabble.com/problem-with-rtsp-with-audio-and-video-td4672324.html)

need your help @Ullaakut

**Comment by Ullaakut** [comment]
Thanks @sidisrikk !

What exactly is the issue? :) I don't see a problem in your screenshots

**Comment by sidisrikk** [comment]
**Thanks**

**Comment by Ullaakut** [comment]
If you are interested in this feature, feel free to create another issue titled something like `Add audio support`, and maybe someone will be interested in implementing it, who knows :)
