### ISSUE TITLE
Outputting streams from multiple IP cameras to a web browser

### ISSUE THREAD

**Issue by pranavlal** [Ullaakut/RTSPAllTheThings#69]
Hi,
I have 10 IP cameras. I want to send their streams to the server and them view them on a web page. Is this the right tool for this task?

**Comment by Ullaakut** [comment]
Mh, most likely not. This tool can be used to broadcast your streams if they aren't accessible from the outside of your network, but that's about it.

What you need is a web interface for viewing RTSP streams.

Here are my suggestions (open source and free):

* https://zoneminder.com/
* https://www.ispyconnect.com/
* https://shinobi.video/

Or you can also buy an NVR (Network Video Recorder) and plug it in your network, most of them provide a web interface to view the streams, on top of keeping records of your streams.
