### ISSUE TITLE
Is there an HTTP Streaming feature

### ISSUE THREAD

**Issue by ai4581532** [Ullaakut/RTSPAllTheThings#71]
> Q: The RTSPALLTT can stream online video like "http://10.9.242.59:8080/shangchang/st016/st016-sc1.mp4" ？

**Comment by Ullaakut** [comment]
Hi @ai4581532,

As its name implies, _RTSPATT_ streams using the **RTSP** protocol, and does not support HTTP streaming. In order to achieve that, you would either need to contribute to this repository by opening a PR, or to use another tool.

**Comment by ai4581532** [comment]
Sorry, I mean，Is it possible to run like this  “./rtspatt -i http://10.9.242.59:8080/st016/st016-sc1.mp4 -l 172.100.100.12 -b 18554”，think you

**Comment by Ullaakut** [comment]
Ah! I see. Well unfortunately, HTTP input is not yet supported either, but it could be quite an easy feature to add. If you are familiar with gstreamer, you can do so by simply changing the source of the internal pipeline :)
