### ISSUE TITLE
Support multi-streaming

### ISSUE THREAD

**Issue by Rakiah** [Ullaakut/RTSPAllTheThings#75]
Hello, do you think it would be possible to stream multiple files/rtsp sources but on only one port and on the same docker container ? so that we could have different paths for different rtsp source like
rtsp://localhost/file1
rtsp://localhost/file2

**Comment by Ullaakut** [comment]
RTSPATT doesn't currently support multi-route streaming at the moment, however it could be added if someone is interested in implementing that feature.

Let me know if you would like to contribute and add this to RTSPATT :)
