### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by saloponov** [Ullaakut/RTSPAllTheThings#77]
After 12 minutes of streaming, the container takes up more than 5 GB of RAM. All streams fell after memory overflow. I use next docker-compose file for creating stream:

    image: ullaakut/rtspatt:latest
    volumes:
      - "./camera-emulator/videos/:/videos/"
    environment:
      RTSP_ADDRESS: 0.0.0.0
      RTSP_PORT: 19554
      RTSP_USERNAME: admin
      RTSP_PASSWORD: 123456
      RTSP_FRAMERATE: 30
      RTSP_RESOLUTION: 1280x720
      INPUT: /videos/cars.mp4
    ports:
      - "19554:19554"

**Comment by saloponov** [comment]
After 12 minutes of streaming, the container takes up more than 5 GB of RAM. All streams falled after memory overflow. I use next docker-compose file for creating stream:
```  camera-emulator-cars:
    image: ullaakut/rtspatt:latest
    volumes:
      - "./camera-emulator/videos/:/videos/"
    environment:
      RTSP_ADDRESS: 0.0.0.0
      RTSP_PORT: 19554
      RTSP_USERNAME: admin
      RTSP_PASSWORD: 123456
      RTSP_FRAMERATE: 30
      RTSP_RESOLUTION: 1280x720
      INPUT: /videos/cars.mp4
    ports:
      - "19554:19554"
```

**Comment by Ullaakut** [comment]
Hi @saloponov,

Thanks for reporting this.

Have you been able to observe the containers for more than 12 minutes? RTSPATT has been running in production for over two years at my former company without any complaints about memory leaks, so I'm not convinced that there is a leak.

My guess is that memory usage simply increases as the videos you are streaming are buffered in the memory.

Let me know if you have some metrics over a longer time period that I could take a look at, and thanks for opening this issue :)

**Comment by shubjain26** [comment]
Hi @Ullaakut ,

Thanks a lot for creating this, it's really helpful.
As @saloponov  mentioned, I am also observering memory leaks.

Within 5 mins, the container size reaches 10 GB

My Docker run command :
`docker run -it -e INPUT=/videos/vid.avi -v `pwd`/videos:/videos -p 8554:8554 ullaakut/rtspatt
`
##########################
Container Log
##########################
```
Server configuration:
Address:	0.0.0.0
Port:		8554
Route:		/live.sdp
Username:	
Password:	
Auth method:	basic
Input:		/videos/khadim.avi
Input type:	file

H264 encoding with:
Framerate:	2
Launching stream with the following pipeline: ( appsrc name=mysrc ! decodebin ! videorate ! video/x-raw,framerate=2/1 ! capsfilter ! queue ! x264enc speed-preset=superfast ! rtph264pay name=pay0 pt=96  )
Stream ready at rtsp://0.0.0.0:8554/live.sdp
```




![Screenshot from 2020-03-26 00-58-23](https://user-images.githubusercontent.com/16733195/77577534-fb96cf00-6efc-11ea-8754-6cdbff2fca95.png)

**Comment by Ullaakut** [comment]
Hi @shubjain26, thanks for the detailed report! I am able to reproduce this issue, but it's unclear why it happens. I'm guessing it's some kind of issue with Gstreamer, I'll look into it when I have some time :)
