### ISSUE TITLE
When hosting container in the cloud, and using INPUT container crashes

### ISSUE THREAD

**Issue by esttenorio** [Ullaakut/RTSPAllTheThings#78]
I'm trying to mock IP cameras by hosting the container with the rtspAllTheThings image on the cloud for testing purposes. There are 2 scenarios:

- when using the env INPUT param for setting the filepath the container crashes. Since it crashes I'm not able to test the stream using VLC. These were logs I was able to retrieve for this scenario before the container crashed:

```
0:00:01.593772825 [332m    1[00m 0x7f627416bde0 [33;01mWARN   [00m [00m             qtdemux qtdemux_types.c:233:qtdemux_type_get:[00m unknown QuickTime node type .TIM
0:00:01.593798525 [332m    1[00m 0x7f627416bde0 [33;01mWARN   [00m [00m             qtdemux qtdemux_types.c:233:qtdemux_type_get:[00m unknown QuickTime node type .TSC
0:00:01.593806726 [332m    1[00m 0x7f627416bde0 [33;01mWARN   [00m [00m             qtdemux qtdemux_types.c:233:qtdemux_type_get:[00m unknown QuickTime node type .TSZ
0:00:01.593873626 [332m    1[00m 0x7f627416bde0 [33;01mWARN   [00m [00m             qtdemux qtdemux.c:3031:qtdemux_parse_trex:<qtdemux0>[00m failed to find fragment defaults for stream 1
0:00:01.660877133 [332m    1[00m 0x7f627416bde0 [33;01mWARN   [00m [00m             basesrc gstbasesrc.c:2445:gst_base_src_update_length:<source>[00m processing at or past EOS
```
- when setting my own pipeline using GST_PIPELINE which is kinda similar to what the tool generates, it works. It doesn't crash. 
PIPELINE: `filesrc location=/mount/media/testvideo.mp4 ! decodebin ! queue ! x264enc speed-preset=superfast ! rtph264pay name=pay0 pt=96`

In both scenarios, it works fine when using `videotestsrc` even with user and password and with specific patterns. So INPUT=pattern:pinwheel works fine. There's something wrong with the `filesrc` processing when using INPUT.

Also when testing locally works fine too in both scenarios.

Do you have a clue about what might be going on here?

Thank you so much for this tool, once I'm done with my project I will publish an article explaining how to store this container on the cloud.

**Comment by Ullaakut** [comment]
Hi @esttenorio!

Unfortunately I haven't worked much on this project for a long time and my Gstreamer skills are very rusty. Since it's an issue I couldn't reproduce, I'm not sure what I can do to help at the moment.

I'm really sorry I can't help, and I hope someone else can help in this thread 😅
